[build]
  command = "npm run build"  # Specify the build command for your project
  publish = "build/"

[dev]  
  # Set the development server command and port
  command = "npm start"
  port = 3000      